channels:
- conda-forge
dependencies:
- python=3.10.13
- pip<=23.3.1
- pip:
  - mlflow==2.8.1
  - cloudpickle==2.2.1
  - numpy==1.26.4
  - packaging==23.2
  - pandas-ta==0.3.14b0
  - pandas==2.1.4
  - psutil==5.9.8
  - pyyaml==6.0.1
  - scikit-learn==1.3.0
  - scipy==1.12.0
  - xgboost==2.0.3
name: mlflow-env
