name: stock_predictor
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas=2.1.4
  - pandas-ta=0.3.14b
  - hydra-core=1.3.2
  - matplotlib=3.8.2
  - scikit-learn=1.3.0
  - xgboost=2.0.3
  - mlflow=2.8.1
  - jupyterlab=4.0.9
  - pytest=7.4.0
  - yfinance=0.2.37
  - psycopg2=2.9.9
  - streamlit=1.32.1
  - pip=23.3.1
  - pip:
      - wandb==0.16.0
      - hydra-joblib-launcher==1.2.0
      - apache-airflow[postgres,celery]==2.8.3
